config/routes.rb
Shadowmsg::Application.routes.draw do
  devise_for :users, :controllers => {omniauth_callbacks: 'omniauth_callbacks'}
  root to: "welcome#index"
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
  resources :messages
  get 'new_message'=> 'messages#new'
  get 'msg_read' => 'messages#msg_read'
  get 'privacy' => 'privacy#show'
  
end

app/models/concerns/message.rb
class Message
	include ActiveModel::Conversion
	extend ActiveModel::Naming

	attr_accessor  :body, :self_destruct_in_seconds, :to

	def Message.global_message
		REDIS.lrange "global_messages", 0, 4
	end

	def initialize( body = nil, self_destruct_in_seconds = nil)
		
		@body = body
		@self_destruct_in_seconds = self_destruct_in_seconds
		
	end

	#redirect to create message page after login, add a special screen after message has been read, messages show available to unauthenticated users, create a anonymous list of previous 5 messages sent(fixed_array).
	def Message.find(id)
		body = REDIS.get id
		expire_in = id.split(":").last.to_i
		if REDIS.get("#{id}:read_flag").nil?
			REDIS.expire id, expire_in
			REDIS.expire "#{id}:read_flag", expire_in
      REDIS.set("#{id}:read_flag", true)

		end
		return body
	end

	def save
		#Telapi::Message.create('{to_number}', '{from_number}', '{body}')
		id = [SecureRandom.hex(14), @self_destruct_in_seconds.to_s].join(":")
		REDIS.set message_key_for(id),self.body
		REDIS.lpush global_messages, self.body
		REDIS.ltrim global_messages, 0, 2
		return message_key_for(id)
	end

	def presisted?
		false
	end

	protected

	def global_messages
		"global_messages"
	end

	def message_key_for(id)
		"messages:#{id}"
	end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
	
	def new 
		@message = Message.new
		authorize @message
	end

	def show
		if Message.find(params[:id]).nil?
			redirect_to msg_read_path
		else
			@message = Message.find(params[:id]) 
		end  
	end

	def create
		Bitly.use_api_version_3
		bitly = Bitly.client
		@message = Message.new(params[:message][:body], params[:message][:self_destruct_in_seconds])
		authorize @message
		message_id = @message.save
		u = bitly.shorten("http://www.shadowmsg.com/messages/#{message_id}").short_url
		
		Telapi::Message.create(params[:message][:to], '+19728537076', "Hi, #{current_user.name} has sent you a Shadow message, #{u}")
		# request_data = { :To => params[:message][:to], :From => "[+16173263477]", :Body => "Hi, #{current_user.name} has sent you a Shadow message,  #{message_url(id: message_id)}", :Token => ENV['TELAPI_TOKEN'] }
		# r = HTTParty.post("https://heroku.telapi.com/send_sms", :body => request_data)
		puts message_id
		
		
		redirect_to new_message_url
		
	end
end

app/helpers/message_helper.rb
module MessageHelper
end

app/views/messages/msg_read.html.erb
<h1> You have already viewed this message, and may not open it again. </h1>

app/views/messages/new.html.erb
<h1>New Message</h1>
<div class = 'col-md-8'>
	<%= form_for @message, url: messages_url do |f| %>
		<div class = "form-group">
			<%= f.label :to %>
      <%= f.text_field :to, class: 'form-control', placeholder: "Enter Phone Number (111)-222-3333" %>
		</div>
		<div class ="form-group">
			<%= f.label :body %>
			<%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter message" %>
		</div>
		<div class="form-group">
			<%= f.select :self_destruct_in_seconds, options_for_select((20..30)) %>
		</div>
					
		<%= f.submit "Send", class: 'btn btn-success' %>
		
	<% end %>
</div>

app/views/messages/show.html.erb

	<p><%= @message %></p>
